-- Feedback de usuários: bug, conteúdo errado, troca de vídeo, sugestão (docs/13-feedback-usuarios.md).
--
-- SQL portável (ANSI) pelo mesmo motivo da V1: as mesmas migrations rodam em Postgres e em H2
-- no modo de compatibilidade PostgreSQL.
--
-- `node_id` é opcional: nem todo feedback é sobre um nó (bug de app, sugestão de funcionalidade).
-- Quando presente, referencia o nó já ingerido do currículo versionado (D11) — nada de nó
-- hardcoded aqui.
CREATE TABLE feedback (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL REFERENCES app_user (id),
    node_id      BIGINT       REFERENCES node (id),
    category     VARCHAR(32)  NOT NULL,
    message      VARCHAR      NOT NULL,
    status       VARCHAR(16)  NOT NULL DEFAULT 'ABERTO',
    created_at   TIMESTAMP    NOT NULL,
    decided_at   TIMESTAMP,
    decided_by   BIGINT       REFERENCES app_user (id)
);

CREATE INDEX idx_feedback_status ON feedback (status, created_at);
