-- Cadastro aberto com senha própria e verificação por e-mail (#81, revisita D36/D37).
--
-- SQL portável (ANSI) pelo mesmo motivo da V1: as mesmas migrations rodam em Postgres e em H2
-- no modo de compatibilidade PostgreSQL.

-- 1) O e-mail que identifica a CONTA, e não a identidade.
--
-- A D36 fixou que a chave da identidade é (provider, subject) e que e-mail NUNCA vincula contas.
-- Com senha própria essa regra passa a produzir o defeito que ela existia para evitar: quem já
-- entrou pelo Google e depois se cadastra com o mesmo endereço ganharia uma segunda conta vazia e
-- acharia que perdeu o progresso. A coluna é o que permite dizer "esta conta já é dona deste
-- endereço" sem transformar `user_identity.email` — que pode vir de relay da Apple, ou não vir —
-- em chave.
--
-- Só entra aqui e-mail VERIFICADO. Endereço digitado e não confirmado não vincula nada; se
-- vinculasse, digitar o endereço de outra pessoa no cadastro daria acesso à conta dela.
ALTER TABLE app_user ADD COLUMN primary_email VARCHAR(320);

-- Backfill: as contas que já existem ganham o endereço verificado que já têm. Sem isto, o
-- primeiro cadastro por senha com o e-mail de uma conta Google existente criaria a conta paralela
-- que a coluna veio impedir.
UPDATE app_user
   SET primary_email = (
        SELECT MIN(LOWER(i.email))
          FROM user_identity i
         WHERE i.user_id = app_user.id
           AND i.email_verified = TRUE
           AND i.email IS NOT NULL
           AND i.email <> '');

-- Duas contas podem ter hoje o mesmo e-mail verificado em provedores diferentes — é exatamente o
-- que a ausência de merge (D36) permitia. A UNIQUE abaixo recusaria a migration inteira por causa
-- disso, então a conta mais antiga fica com o endereço e as outras ficam sem: nenhuma some, e o
-- vínculo passa a valer dali para a frente. Fundir progresso de contas já usadas seria decisão de
-- produto, não de migration.
UPDATE app_user
   SET primary_email = NULL
 WHERE primary_email IS NOT NULL
   AND id <> (SELECT MIN(o.id) FROM app_user o WHERE o.primary_email = app_user.primary_email);

-- UNIQUE aceita vários NULL nos dois bancos: conta de demonstração (#62) e conta de provedor sem
-- e-mail verificado continuam existindo sem endereço, como sempre existiram.
ALTER TABLE app_user ADD CONSTRAINT uk_app_user_primary_email UNIQUE (primary_email);

-- 2) A senha, fora de `user_identity`.
--
-- Tabela própria para que a linha de identidade continue significando só "quem é", e para que
-- apagar a credencial não apague a identidade: quem trocar a senha por login social não perde o
-- histórico da conta. O hash vem do DelegatingPasswordEncoder do Spring Security e chega com o
-- prefixo do algoritmo ({bcrypt}...), então trocar de algoritmo depois é rehash no login e não
-- migration — daí a coluna ser larga o bastante para um prefixo maior que o de hoje.
CREATE TABLE password_credential (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_id    BIGINT       NOT NULL REFERENCES user_identity (id),
    password_hash  VARCHAR(200) NOT NULL,
    updated_at     TIMESTAMP    NOT NULL,
    CONSTRAINT uk_password_credential_identity UNIQUE (identity_id)
);

-- 3) O `login_token` deixa de ser só "link de entrada".
--
-- O que já estava certo nele fica: guarda só o hash, é de uso único e vence. O que muda é ele
-- passar a servir a três propósitos, e o propósito ser conferido no consumo — link de verificação
-- apresentado na rota de entrada não pode autenticar ninguém, e link de redefinição não pode
-- virar login. Sem a coluna, os três seriam intercambiáveis e o mais curto valeria pelo mais
-- longo.
--
-- DEFAULT 'ENTRADA' para as linhas que já existem: elas são links de entrada emitidos pela #52,
-- e o default também mantém funcionando o `scripts/mint-dev-login.mjs`, que insere sem a coluna.
ALTER TABLE login_token ADD COLUMN purpose VARCHAR(16) NOT NULL DEFAULT 'ENTRADA';

CREATE INDEX idx_login_token_user_purpose ON login_token (user_id, purpose);
