-- Coleta de uso do app (#84, D50): quantas pessoas chegam, de onde vêm e com o quê.
--
-- SQL portável (ANSI) pelo mesmo motivo da V1: as mesmas migrations rodam em Postgres e em H2
-- no modo de compatibilidade PostgreSQL.
--
-- Duas tabelas, e não uma, porque elas têm vidas diferentes: `usage_event` é a linha crua, com
-- chave de visita e às vezes `user_id`, e vive 90 dias; `usage_daily` é a contagem por dia, sem
-- nada que aponte para pessoa nenhuma, e fica. Sem a segunda, o painel varreria a tabela grande
-- a cada abertura — e a retenção curta da primeira apagaria o histórico junto.
--
-- O QUE NÃO EXISTE AQUI, e é o ponto da issue: **coluna de endereço de IP**. O IP é lido na
-- requisição, serve para derivar país e para compor a chave de visita, e é descartado no mesmo
-- método. Há teste que varre o schema e falha se uma coluna com cara de IP aparecer
-- (`UsageSemIpTest`) — a ausência aqui é requisito, não esquecimento.

CREATE TABLE usage_event (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at   TIMESTAMP   NOT NULL,
    -- Dia do mesmo relógio que define "hoje" no resto do app: é por ele que a agregação e o
    -- expurgo recortam, e é o que o painel (fatia 2) vai ler.
    occurred_on   DATE        NOT NULL,
    -- PAGINA (mudança de rota, vinda do web) ou um dos eventos de funil, que só o backend emite.
    event_type    VARCHAR(32) NOT NULL,
    -- Caminho NORMALIZADO contra a lista de rotas conhecidas do app. Nunca o que o cliente
    -- mandou: `/confirmar-email/<token>` viraria token de confirmação gravado em tabela de
    -- métrica, que é o oposto do que este arquivo existe para fazer.
    path          VARCHAR(120) NOT NULL,
    -- Hash de (IP + User-Agent + sal do dia). O sal é sorteado por dia e NUNCA persistido: o
    -- hash não é reversível, e a mesma pessoa em dois dias diferentes não é ligável — de
    -- propósito. É o que permite contar visitantes sem cookie e sem identificador estável.
    visit_key     VARCHAR(64) NOT NULL,
    -- Só em evento de conta autenticada. Sem FK: o evento é registro histórico, e a exclusão de
    -- conta apaga estas linhas explicitamente (`AccountService.delete`) em vez de depender de
    -- cascade — é a mesma escolha da trilha de decisão da V13.
    user_id       BIGINT,
    device        VARCHAR(16) NOT NULL,
    browser       VARCHAR(32) NOT NULL,
    os            VARCHAR(32) NOT NULL,
    language      VARCHAR(16) NOT NULL,
    -- Código ISO de duas letras, ou 'ZZ'. Desconhecido é valor válido e categoria própria: em
    -- dev e no CI não há base de geolocalização, e o app precisa subir e coletar assim mesmo.
    country       VARCHAR(2)  NOT NULL,
    region        VARCHAR(64) NOT NULL,
    -- Só o HOST do referrer, nunca a URL: caminho de terceiro é conteúdo de navegação alheia.
    referrer_host VARCHAR(120) NOT NULL,
    utm_source    VARCHAR(60) NOT NULL,
    utm_medium    VARCHAR(60) NOT NULL,
    utm_campaign  VARCHAR(60) NOT NULL
);

-- O índice que a agregação e o expurgo usam: os dois recortam por dia.
CREATE INDEX idx_usage_event_day ON usage_event (occurred_on);
-- O que faz `DELETE /api/me` não varrer a tabela inteira.
CREATE INDEX idx_usage_event_user ON usage_event (user_id);

-- Contagem por dia x dimensão. Uma linha por (dia, dimensão, valor) — formato longo, e não uma
-- coluna por dimensão, porque dimensão nova (idioma, navegador) passa a ser dado e não migration.
CREATE TABLE usage_daily (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_on     DATE        NOT NULL,
    -- CAMINHO, PAIS, DISPOSITIVO, ORIGEM ou EVENTO.
    dimension       VARCHAR(16) NOT NULL,
    dimension_value VARCHAR(120) NOT NULL,
    -- Quantos eventos, e quantas visitas distintas os produziram. Os dois, porque "300 acessos"
    -- e "300 pessoas" são respostas diferentes para a mesma pergunta.
    events          BIGINT      NOT NULL,
    visits          BIGINT      NOT NULL,
    CONSTRAINT uq_usage_daily UNIQUE (occurred_on, dimension, dimension_value)
);

CREATE INDEX idx_usage_daily_day ON usage_daily (occurred_on);
