-- Saúde do site (#86): o que a aplicação consegue observar sobre si mesma.
--
-- SQL portável (ANSI) pelo mesmo motivo da V1: as mesmas migrations rodam em Postgres e em H2 no
-- modo de compatibilidade PostgreSQL.
--
-- O QUE NÃO EXISTE AQUI, e é requisito e não esquecimento: **coluna de endereço de IP** e
-- **coluna de conta**. Contar requisição não é observar pessoa. `UsageSemIpTest` varre toda
-- migration e reprova o build se uma coluna com cara de IP aparecer — e a régua da #84 (D50) vale
-- igual aqui: nenhuma linha destas tabelas diz quem fez a requisição, nem de onde.

-- Uma linha por (hora, rota). A hora é o recorte porque o painel pergunta "quantas requisições por
-- hora" e "o site esteve de pé nesta janela" — minuto seria tabela grande para responder o mesmo,
-- e dia esconderia exatamente a queda de vinte minutos que interessa achar.
CREATE TABLE http_stat_hourly (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Início da hora, em UTC, sempre com minuto e segundo zerados.
    hour_start     TIMESTAMP    NOT NULL,
    -- O PADRÃO da rota que o Spring casou (`/api/admin/usuarios/{id}/status`), nunca o caminho
    -- que chegou. Não é arrumação: é a mesma guarda do `UsagePaths` na #84 — gravar o caminho cru
    -- poria token de confirmação de e-mail dentro de uma tabela de métrica. Requisição que não
    -- casou rota nenhuma (404) vira '(sem rota)'.
    path           VARCHAR(160) NOT NULL,
    requests       BIGINT       NOT NULL,
    -- 4xx e 5xx separados porque respondem perguntas diferentes: 4xx é quem chama pedindo errado
    -- (e um pico de 401/403 é sinal de ataque, não de defeito); 5xx é o app errando, e é só ele
    -- que entra na disponibilidade.
    client_errors  BIGINT       NOT NULL,
    server_errors  BIGINT       NOT NULL,
    -- Soma e máximo dos tempos, em milissegundos. A soma dá a média do período sem guardar
    -- amostra nenhuma; o máximo é o que a média sempre esconde.
    total_ms       BIGINT       NOT NULL,
    max_ms         BIGINT       NOT NULL,
    -- Histograma de latência, escada FIXA (ver dev.fos.service.HttpStats). Colunas, e não formato
    -- longo como `usage_daily`, porque aqui a escada é do programa e não do dado: mudá-la é
    -- migration de propósito — somar contagens de duas escadas diferentes daria um p95 inventado.
    -- É o histograma que faz o p95 do PERÍODO ser somável; p95 por hora não se soma nem se
    -- promedia.
    bucket_25      BIGINT       NOT NULL,
    bucket_50      BIGINT       NOT NULL,
    bucket_100     BIGINT       NOT NULL,
    bucket_250     BIGINT       NOT NULL,
    bucket_500     BIGINT       NOT NULL,
    bucket_1000    BIGINT       NOT NULL,
    bucket_2500    BIGINT       NOT NULL,
    bucket_acima   BIGINT       NOT NULL,
    CONSTRAINT uq_http_stat_hourly UNIQUE (hour_start, path)
);

-- O índice do painel e do expurgo: os dois recortam por hora.
CREATE INDEX idx_http_stat_hourly_hora ON http_stat_hourly (hour_start);

-- Toda subida da aplicação vira uma linha. É o que transforma "reiniciou sozinho de madrugada" de
-- suspeita em fato: sem isto, uma queda de dois minutos às 3h não deixa rastro nenhum depois que
-- o log da plataforma rotaciona.
CREATE TABLE app_start (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at  TIMESTAMP    NOT NULL,
    -- Perfis ativos do Spring. Serve para separar, no histórico, a subida de produção da subida
    -- de quem rodou o app na própria máquina contra o mesmo banco.
    profiles    VARCHAR(120) NOT NULL
);

CREATE INDEX idx_app_start_quando ON app_start (started_at);
