-- Freeze de streak (#99, D55): o dia perdido que foi perdoado.
--
-- SQL portável (ANSI) pelo mesmo motivo da V1: as mesmas migrations rodam em Postgres e em H2 no
-- modo de compatibilidade PostgreSQL.
--
-- Uma linha por dia coberto. Não é cache do cálculo — o streak continua sendo derivado do
-- `drill_log` a cada leitura — e sim o LIVRO-CAIXA do saldo: um freeze gasto continua gasto depois
-- que a corrente que ele salvava quebrou. Sem esta tabela o saldo seria "por corrente" e não "por
-- mês", e bastaria deixar a sequência morrer para ganhar freeze novo.
--
-- Sem coluna de saldo, de propósito: saldo é `freezes-por-mês menos as linhas do mês`, e guardá-lo
-- criaria uma segunda verdade para a mesma pergunta.
CREATE TABLE streak_freeze (
    id          BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT    NOT NULL REFERENCES app_user (id),
    -- O dia SEM treino que foi perdoado. Nunca é hoje: o dia ainda não acabou.
    covered_on  DATE      NOT NULL,
    -- Quando o app percebeu a cobertura. Não é `covered_on`: o cálculo roda na leitura seguinte
    -- do streak, que pode ser dias depois — e a diferença entre os dois é o que conta a história.
    created_at  TIMESTAMP NOT NULL,
    -- O que torna o cálculo idempotente: recalcular o mesmo dia não cobra duas vezes. É a chave
    -- que permite o cálculo rodar em TODA leitura do streak sem inflar a tabela.
    CONSTRAINT uq_streak_freeze UNIQUE (user_id, covered_on)
);
