-- Diário de treino (#114, D56/D57/D58): a sessão vira a unidade do que aconteceu no tatame.
--
-- SQL portável (ANSI) pelo mesmo motivo da V1: as mesmas migrations rodam em Postgres e em H2 no
-- modo de compatibilidade PostgreSQL.
--
-- Até aqui o único registro de treino era por nó (`drill_log`), e isso deixava de fora tudo que
-- não é técnica do currículo: rola solta, físico, aula de algo que ainda não tem nó. Sem lugar
-- para o resto, o registro não acontece — e é o registro que alimenta a camada de retenção.
--
-- O QUE NÃO EXISTE AQUI, e é escolha: tabela paralela de "técnica treinada". Técnica vinculada
-- continua sendo `drill_log`, agora com `session_id` (D56a). Um segundo registro de "treinei isto"
-- daria ao SRS duas verdades sobre o mesmo fato, e só uma delas agendaria revisão.
CREATE TABLE training_session (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT      NOT NULL REFERENCES app_user (id),
    -- Dia do treino, nunca futuro — a mesma regra que `drill_log.drilled_on` já seguia. Sem
    -- restrição de unicidade com `user_id`, de propósito: manhã e noite são DUAS sessões, e o
    -- streak conta dias distintos, não linhas.
    trained_on       DATE        NOT NULL,
    -- AULA | DRILL | ROLA | FISICO | DESCANSO | OUTRO. `DESCANSO` é o que impede o abuso trivial
    -- da D58: dia anotado sem treino fica no diário e NÃO conta como dia de treino.
    kind             VARCHAR(16) NOT NULL,
    duration_minutes INTEGER,
    -- BEM | NEUTRO | MAL. Guardado e mostrado, nunca interpretado (D57): sem meta, sem alerta e
    -- sem correlação apresentada como causa.
    feeling          VARCHAR(16),
    -- NUMERIC e não ponto flutuante: peso é dinheiro, não medida aproximada. Opcional e POR
    -- SESSÃO, nunca diário — pesar no dia do treino é o hábito real, e um tracker diário seria
    -- outro produto, com outra régua de risco (D57).
    --
    -- Peso e sensação são DADO REFERENTE À SAÚDE (LGPD, art. 5º, II): ficam só na conta de quem
    -- escreveu, `DELETE /api/me` os leva junto, e a coleta da D50 e o painel da D52 nunca os veem.
    -- Está escrito em docs/11-privacidade.md, e mexer aqui exige reescrever aquela seção.
    weight_kg        NUMERIC(5,2),
    learned          VARCHAR(2000),
    improve          VARCHAR(2000),
    created_at       TIMESTAMP   NOT NULL,
    updated_at       TIMESTAMP   NOT NULL
);

CREATE INDEX idx_training_session_user_date ON training_session (user_id, trained_on);

-- ANULÁVEL, e é o que dispensa backfill: os drills gravados antes desta feature entram no diário
-- como registro avulso, sem migration de dados e sem sessão inventada para eles. Continua
-- anulável depois, porque registrar pela tela do nó segue sendo caminho de primeira classe.
ALTER TABLE drill_log ADD COLUMN session_id BIGINT REFERENCES training_session (id);

CREATE INDEX idx_drill_log_session ON drill_log (session_id);
