-- Autenticação do app mobile (#139, D68).
--
-- SQL portável (ANSI) pelo mesmo motivo da V1: as mesmas migrations rodam em Postgres e em H2
-- no modo de compatibilidade PostgreSQL.

-- 1) O token do app.
--
-- Mesmo princípio do `login_token`: o valor sorteado vai para o aparelho, e aqui fica só o
-- SHA-256 em hexadecimal. Quem ler o banco não entra como ninguém.
--
-- Aponta para a IDENTIDADE, e não para a conta: é por ela que o `CurrentUserProvider` resolve o
-- usuário, e é ela que o `mergeIdentityInto` move de conta. Pendurado na conta, o token ficaria
-- vivo na conta que a pessoa deixou de usar.
--
-- Revogar é apagar a linha. Token revogado e token que nunca existiu respondem o mesmo 401, e
-- não há tela que precise distinguir os dois — ao contrário do link de e-mail, que diz "já usado".
CREATE TABLE mobile_token (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_id   BIGINT      NOT NULL REFERENCES user_identity (id),
    token_hash    VARCHAR(64) NOT NULL,
    created_at    TIMESTAMP   NOT NULL,
    -- Atualizado no máximo uma vez por dia: é ele que vence o token por desuso, e gravar a cada
    -- requisição faria toda leitura do app virar escrita.
    last_used_at  TIMESTAMP   NOT NULL,
    CONSTRAINT uk_mobile_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_mobile_token_identity ON mobile_token (identity_id);

-- 2) O refresh token da Apple, para revogar o acesso quando a conta é excluída.
--
-- Fora de `user_identity` pelo mesmo motivo da senha em `password_credential`: a identidade diz
-- só "quem é". Ao contrário da senha, este valor não pode virar hash — ele precisa ser
-- REENVIADO à Apple na revogação —, e é por isso que ele só serve para revogar e não abre sessão
-- nenhuma no app.
CREATE TABLE apple_credential (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_id    BIGINT        NOT NULL REFERENCES user_identity (id),
    refresh_token  VARCHAR(1024) NOT NULL,
    updated_at     TIMESTAMP     NOT NULL,
    CONSTRAINT uk_apple_credential_identity UNIQUE (identity_id)
);
