-- Esquema inicial do FightOssStreak.
--
-- SQL deliberadamente portável (ANSI + IDENTITY) porque o mesmo conjunto de migrations roda
-- em Postgres (alvo real) e em H2 no modo de compatibilidade PostgreSQL (perfis dev e test).
-- Isso evita o clássico "passa no teste, quebra em produção" por divergência de schema.
--
-- Pré-requisitos formam um GRAFO, não uma hierarquia (docs/01-stack-tecnica.md):
-- um nó tem múltiplos pré-requisitos e múltiplos sucessores, daí a tabela de arestas.

CREATE TABLE app_user (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label       VARCHAR(120) NOT NULL,
    created_at  TIMESTAMP    NOT NULL
);

CREATE TABLE curriculum_module (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(16)  NOT NULL UNIQUE,
    title        VARCHAR(200) NOT NULL,
    summary      VARCHAR      NOT NULL,
    order_index  INT          NOT NULL
);

CREATE TABLE node (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id            BIGINT       NOT NULL REFERENCES curriculum_module (id),
    code                 VARCHAR(16)  NOT NULL UNIQUE,
    title                VARCHAR(300) NOT NULL,
    belt                 VARCHAR(16)  NOT NULL,
    concept              VARCHAR      NOT NULL,
    order_index          INT          NOT NULL,
    -- ALL: todos os pré-requisitos concluídos. ANY: pelo menos um (ver D13).
    unlock_rule          VARCHAR(8)   NOT NULL DEFAULT 'ALL',
    -- Vídeo é sempre embed do player oficial do YouTube (D7). NULL = ainda não catalogado.
    video_youtube_id     VARCHAR(32),
    video_title          VARCHAR(300),
    video_channel        VARCHAR(200),
    video_start_seconds  INT
);

CREATE INDEX idx_node_module ON node (module_id);

CREATE TABLE node_prereq (
    node_id         BIGINT NOT NULL REFERENCES node (id),
    prereq_node_id  BIGINT NOT NULL REFERENCES node (id),
    PRIMARY KEY (node_id, prereq_node_id)
);

CREATE TABLE quiz_question (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id      BIGINT  NOT NULL REFERENCES node (id),
    prompt       VARCHAR NOT NULL,
    explanation  VARCHAR NOT NULL,
    order_index  INT     NOT NULL
);

CREATE INDEX idx_quiz_question_node ON quiz_question (node_id);

CREATE TABLE quiz_option (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id  BIGINT  NOT NULL REFERENCES quiz_question (id),
    label        VARCHAR NOT NULL,
    correct      BOOLEAN NOT NULL,
    order_index  INT     NOT NULL
);

CREATE INDEX idx_quiz_option_question ON quiz_option (question_id);

CREATE TABLE user_progress (
    user_id          BIGINT      NOT NULL REFERENCES app_user (id),
    node_id          BIGINT      NOT NULL REFERENCES node (id),
    status           VARCHAR(16) NOT NULL,
    completed_at     TIMESTAMP,
    last_quiz_score  INT,
    updated_at       TIMESTAMP   NOT NULL,
    PRIMARY KEY (user_id, node_id)
);

-- Agenda de repetição espaçada (SM-2 adaptado). O backend é a fonte da verdade;
-- shared/domain replica o cálculo apenas para preview otimista na UI.
CREATE TABLE srs_review (
    user_id           BIGINT           NOT NULL REFERENCES app_user (id),
    node_id           BIGINT           NOT NULL REFERENCES node (id),
    next_review_on    DATE             NOT NULL,
    interval_days     INT              NOT NULL,
    ease_factor       DOUBLE PRECISION NOT NULL,
    repetitions       INT              NOT NULL,
    last_reviewed_on  DATE,
    PRIMARY KEY (user_id, node_id)
);

CREATE INDEX idx_srs_due ON srs_review (user_id, next_review_on);

CREATE TABLE drill_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES app_user (id),
    node_id     BIGINT      NOT NULL REFERENCES node (id),
    drilled_on  DATE        NOT NULL,
    recall      VARCHAR(16) NOT NULL,
    note        VARCHAR,
    created_at  TIMESTAMP   NOT NULL
);

CREATE INDEX idx_drill_log_user_date ON drill_log (user_id, drilled_on);

-- O aceite é registrado com data E versão do texto: mudança material no disclaimer
-- exige novo aceite (docs/06-disclaimer-responsabilidade.md).
CREATE TABLE disclaimer_acceptance (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL REFERENCES app_user (id),
    version      VARCHAR(32) NOT NULL,
    accepted_at  TIMESTAMP   NOT NULL
);

CREATE INDEX idx_disclaimer_user ON disclaimer_acceptance (user_id);
