-- Dado que faltava para medir os critérios de sucesso do MVP (docs/05-mvp-web-plano.md).
--
-- Duas das quatro métricas não eram calculáveis com o schema anterior, e nenhuma delas dava
-- para reconstruir depois:
--
--   * "nós revisados via sugestão do SRS" exige saber se o nó estava vencido NO MOMENTO do
--     drill. `srs_review.next_review_on` é sobrescrito a cada registro, então a informação
--     desaparece assim que o drill acontece. Tem de ser gravada junto com o drill.
--   * "quiz refeito espontaneamente" exige histórico de tentativas. `user_progress
--     .last_quiz_score` guarda só a última, e um quiz refeito fica indistinguível de um quiz
--     respondido uma única vez.

-- Estado da agenda no instante do registro, não depois.
ALTER TABLE drill_log ADD COLUMN was_due BOOLEAN NOT NULL DEFAULT FALSE;
-- Data que estava agendada quando o drill foi registrado. NULL = nó não tinha revisão agendada
-- (primeiro contato com o nó, antes de qualquer conclusão).
ALTER TABLE drill_log ADD COLUMN due_on DATE;

-- Histórico append-only de tentativas de quiz. `user_progress.last_quiz_score` continua sendo o
-- estado atual; esta tabela é o que permite ver que o nó foi revisitado.
CREATE TABLE quiz_attempt (
    id            BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT    NOT NULL REFERENCES app_user (id),
    node_id       BIGINT    NOT NULL REFERENCES node (id),
    score         INT       NOT NULL,
    passed        BOOLEAN   NOT NULL,
    -- Data do mesmo relógio que define "hoje" no resto do app: é por ela que a janela de
    -- medição é recortada.
    attempted_on  DATE      NOT NULL,
    created_at    TIMESTAMP NOT NULL
);

CREATE INDEX idx_quiz_attempt_user_date ON quiz_attempt (user_id, attempted_on);
