-- Login social e acesso sob aprovação (#24, revisita a D9).
--
-- Duas coisas entram juntas porque uma sem a outra não fecha: a identidade externa diz QUEM é o
-- usuário da requisição, e o estado de acesso diz SE ele entra. Só a identidade transformaria o
-- app em autocadastro — quem tem a URL entra com o Google e vira usuário.
--
-- SQL portável (ANSI) pelo mesmo motivo da V1: as mesmas migrations rodam em Postgres e em H2
-- no modo de compatibilidade PostgreSQL.

-- Estado de acesso da CONTA, não da identidade: se um dia houver merge de provedores, a decisão
-- de liberar continua valendo para a conta inteira.
ALTER TABLE app_user ADD COLUMN access_status VARCHAR(16) NOT NULL DEFAULT 'PENDENTE';
ALTER TABLE app_user ADD COLUMN requested_at TIMESTAMP;
ALTER TABLE app_user ADD COLUMN decided_at TIMESTAMP;

-- A linha semeada pela V2 é o progresso real do autor. Sem isto ela nasceria bloqueada no dia
-- do deploy, e o app trancaria a si mesmo: não haveria conta aprovada para aprovar as outras.
UPDATE app_user
   SET access_status = 'APROVADO',
       requested_at  = created_at,
       decided_at    = created_at;

-- A V2 inseriu `id = 1` explicitamente, e coluna GENERATED BY DEFAULT não avança a sequência
-- quando o valor vem no INSERT. Sem este RESTART, a primeira conta criada por login tentaria
-- `id = 1` de novo e morreria por chave duplicada — não em teste, mas no primeiro usuário além do
-- autor, em produção. Vale igual em Postgres e em H2.
ALTER TABLE app_user ALTER COLUMN id RESTART WITH 2;

-- A chave é o par (provedor, subject). E-mail NÃO é identidade: a Apple entrega
-- @privaterelay.appleid.com quando o usuário esconde o endereço, o Facebook pode não devolver
-- e-mail nenhum, e nome e e-mail só vêm no primeiro consentimento — daí os campos nullable.
CREATE TABLE user_identity (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL REFERENCES app_user (id),
    provider          VARCHAR(32)  NOT NULL,
    provider_subject  VARCHAR(255) NOT NULL,
    email             VARCHAR(320),
    -- Só e-mail verificado decide bootstrap do dono. Sem esta coluna, "e-mail verificado"
    -- seria uma intenção escrita na doc e um `contains()` crédulo no código.
    email_verified    BOOLEAN      NOT NULL DEFAULT FALSE,
    display_name      VARCHAR(200),
    created_at        TIMESTAMP    NOT NULL,
    last_login_at     TIMESTAMP    NOT NULL,
    CONSTRAINT uk_user_identity_provider_subject UNIQUE (provider, provider_subject)
);

CREATE INDEX idx_user_identity_user ON user_identity (user_id);
