-- Entrada por e-mail para quem não tem provedor externo (#52, revisita a D36).
--
-- SQL portável (ANSI) pelo mesmo motivo da V1: as mesmas migrations rodam em Postgres e em H2
-- no modo de compatibilidade PostgreSQL.

-- O token vai no link que a pessoa recebe por e-mail; aqui fica só o hash. Quem ler o banco
-- não consegue entrar como ninguém — e é por isso que a coluna guarda 64 caracteres (SHA-256
-- em hexadecimal) em vez do valor sorteado.
CREATE TABLE login_token (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES app_user (id),
    token_hash  VARCHAR(64) NOT NULL,
    created_at  TIMESTAMP   NOT NULL,
    expires_at  TIMESTAMP   NOT NULL,
    -- Marca o uso em vez de apagar a linha: token reapresentado precisa ser reconhecido como
    -- "já usado", e não como "nunca existiu". A diferença importa para a mensagem na tela.
    used_at     TIMESTAMP,
    CONSTRAINT uk_login_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_login_token_user ON login_token (user_id);
